### ISSUE TITLE
irc_bot singleton

### ISSUE THREAD

**Issue by langel** [langel/botb_irc_bot#26]
could it be possible to make the irc_bot module a singleton?

if so, irc_bot could be loaded into commands instead of it being passed to every single command

**Comment by langel** [comment]
my conclusion is that passing the bot to commands is really dumb
instead commands will return strings
the delegator's guts have been moved inside irc_bot

**Comment by ianremsen** [comment]
that worked

**Comment by langel** [comment]
eventually!
