### ISSUE TITLE
command prefix

### ISSUE THREAD

**Issue by langel** [langel/botb_irc_bot#3]
The old bot uses ! (bang) for a command prefix.  We will most likely keep with this but it is not implemented yet.  Other options are a comma (silly) or the semi-colon (programmer comments?!?).  

Private message commands don't need a prefix; or do they?

**Comment by ianremsen** [comment]
I would say PMs use the bang prefix as well, just so everything is exactly the same, this kind of stuff needs as much cohesion as possible
