### ISSUE TITLE
more refactoring for irc_bot and commands

### ISSUE THREAD

**Issue by langel** [langel/botb_irc_bot#33]
So after all the work I did to try and figure out how to not pass the bot to every command function seems to be null and void for issue #11 

I have an idea tho.

Basically, in order to talk to NickServ a few times and process data (which is required to make sure a nick is registered), the command will need access to the bot.

**Comment by langel** [comment]
I figured it out!  To get around circular dependencies the irc_bot is not requiring irc_commands until it's initialize() method is called.

**Comment by Always8bit** [comment]
Puke u genius
