### ISSUE TITLE
New "ohb" command to show time left and a link to the compo

### ISSUE THREAD

**Issue by SketchMan3** [langel/botb_irc_bot#39]
Since ";ohb" now performs the same function as compo (unless that's just temporary), we could have "ohbt"/"ohct" or "bt"/"ct" commands to show the OHB Time left. 

Also, it would be good if whatever command shows the ohb time left would also provide a link to the battle page.

**Comment by langel** [comment]
There was an attempt made --
https://github.com/langel/botb_irc_bot/pull/47/commits
I wrote up functionality as a comment on that pull request, but forgot to add a link to the battle.  The current bot doesn't like the battle.  Is this a desired evolution?

**Comment by ghost** [comment]
the current bot "doesn't like the battle"? could you clarify, langel? :p

also, question about this: what does the request from the server look like when an OHB is starting, 10 minutes left, 2 minutes left, finished, etc.?

**Comment by langel** [comment]
I'm guessing I meant "doesn't link the battle"

**Comment by langel** [comment]
that link was wrong
you need to click the conversation tab
or maybe this link will work
https://github.com/langel/botb_irc_bot/pull/47
