### ISSUE TITLE
ultrachord command pluck octave 9 crashes bot

### ISSUE THREAD

**Issue by langel** [langel/botb_irc_bot#44]
it was suggested that pluck might use a filter and it's choking on math
which would mean there is a bug with the CLI tool we are utilizing

**Comment by langel** [comment]
from IRC --

> [16:46] <Yuki-chan> Does it use a LADSPA synth?
> [16:47] <Yuki-chan> Because I highly doubt these plucks are native sox!
> [16:47] <puke7777> i don't remember if it was R3M or Savestate that figured that out
> [16:47] <Yuki-chan> Oh wait it does have a native synth
> [16:48] <Yuki-chan> Yeah I could probably try a range of plucks
> [16:48] <Yuki-chan> and see if sox chokes on any
> [16:49] <puke7777> http://sox.sourceforge.net/Docs/Features  <-- it says something about LADSPA on this page
> [16:49] <puke7777> i don't know what that is
> [16:49] == SketchMan3 [~brkbrkbrk@nc-76-3-211-77.dhcp.embarqhsd.net] has quit [Ping timeout: 183 seconds]
> [16:50] <Yuki-chan> Yep
> [16:50] <Yuki-chan> C:\Program Files (x86)\sox-14-4-2>sox -n B:/H/output.wav synth 3 pluck %-20
> [16:50] <Yuki-chan> C:\Program Files (x86)\sox-14-4-2>sox -n B:/H/output.wav synth 3 pluck %-40
> [16:50] <Yuki-chan> C:\Program Files (x86)\sox-14-4-2>sox -n B:/H/output.wav synth 3 pluck %-60
> [16:50] <Yuki-chan> sox FAIL synth: invalid freq
> [16:50] <puke7777> looks like a rabbit hole
> [16:50] <Yuki-chan> Looks like the bot always expects sox to return sound
> [16:50] <Yuki-chan> and crashes when sox returns an error instead
> [16:51] <Yuki-chan> sox's pluck doesn't work with 60 semitones below A=440 Hz

**Comment by jangler** [comment]
What's an example of a command that causes this to happen?

**Comment by ianremsen** [comment]
since commands no longer crash the bot, it just doesn't work now

**Comment by langel** [comment]
using pluck with octave 9 breaks it

**Comment by jangler** [comment]
I had been trying the syntax from the old help message (`;uc <notes> [timbre]`) instead of the actual syntax (`;uc [timbre] <notes>`). Can reproduce now.

**Comment by jangler** [comment]
As mentioned in IRC, [it's an apparently intentional limitation of SoX](https://github.com/jacksonh/sox/blob/master/src/synth.c#L353), so not really a bug.  Best to have the bot just yell at you if you try to pluck too high.

**Comment by langel** [comment]
great investigations!
