### ISSUE TITLE
pix command

### ISSUE THREAD

**Issue by langel** [langel/botb_irc_bot#5]
"pix (string)" will give a url to a custom pic where (string) is the BotBr/chatter's name.

Old bot keeps them on the bot server.  They could be hosted by the new bot or BotB itself.

**Comment by ianremsen** [comment]
It's probably a good idea to keep them on the battleofthebits.org domain

**Comment by Always8bit** [comment]
via upload pix form in the homebunk settings/edit profile area?

**Comment by langel** [comment]
!pix has always been something that strobe handled manually
it's specific to the bot
I could add the feature in botb settings/edit area or we could keep it irc only.

**Comment by ianremsen** [comment]
it's possible you could just provide an imgur url or somewhere else (.club) where it'll always be, you don't have to have it central to one domain

**Comment by ianremsen** [comment]
totally contradicting what i just said
