### ISSUE TITLE
Leading space

### ISSUE THREAD

**Issue by jangler** [langel/botb_irc_bot#52]
The leading spaces before bot responses have bothered me for an eternity! May we purge them?

**Comment by langel** [comment]
For me it's an aesthetic thing.  If the IRC client's background isn't black I think it looks fine.
Removing the leading space should also include removing the trailing space.
I'm open for discussion on this, but for me, personally, it is preferred.

**Comment by jangler** [comment]
Oh, I completely forgot that the bot used a black background—it's just been so long since I used a graphical IRC client. The space makes sense to me now; I'm fine with it.
