### ISSUE TITLE
!entry_id command

### ISSUE THREAD

**Issue by langel** [langel/botb_irc_bot#69]
bot returns link to entry with specific id

**Comment by ghost** [comment]
just interpolate the id into this url:

`http://battleofthebits.org/arena/Entry/poop/${id}/`

(actually works)

**Comment by langel** [comment]
just make a pull request ;D

**Comment by ghost** [comment]
haha, i might (:

**Comment by kleeder** [comment]
looks like sleeparrow didnt make this pull request, but i did. his idea is nice, too, but i used the api the same way as the !entry command just to have it consistent. uhh, hope it works lol o:/
