### ISSUE TITLE
chord command

### ISSUE THREAD

**Issue by langel** [langel/botb_irc_bot#8]
currently "ultrachord (string)" returns a link to a rendered audio file of the given chord parameters in (string)

from the lyceum --
it works like this: 
!ultrachord C3 D#3 G3 

This will produce a choir in C minor, you can change instruments on fly if 
you set notes to "trem" "brass" "choir", choir is default. 

Notes can range from C0 up to C7 
if number is omitted it will pick octave 2.

**Comment by ianremsen** [comment]
I've had a few ideas about ultrachords, but I seem to have forgotten all of them. Will report back.

**Comment by ianremsen** [comment]
OK, an idea I just had is an **extremely** rudimentary progression feature

like "C4 E4 G4 | G3 B3 D4" would play each chord for a second. This seems to be as complicated as I would want to make it, I don't want to make it into a fullblown composing engine/shitpost machine extraordinaire, but the progression feature would be useful.

**Comment by langel** [comment]
[02:41] <puke7> http://sox.sourceforge.net/Docs/Documentation  <-- this might be it actually
[02:42] <puke7> there's an option to set the rate of inputs while mixing
