### ISSUE TITLE
!kudosamount <integer>

### ISSUE THREAD

**Issue by kleeder** [langel/botb_irc_bot#82]
should return number of keys with the amount <integer>

for example:
!kudosamount 1

-> There are currently 84375379845 different keys with 1 kudos.

**Comment by langel** [comment]
but not the keys themselves? :o

**Comment by kleeder** [comment]
if you have 2000 keys with 1 kudos, that might be a bit TOO MUCH.
but !kudosrandom command could return a random key with x kudos if you say !kudosrandom x
