### ISSUE TITLE
!roll command

### ISSUE THREAD

**Issue by viraxor** [langel/botb_irc_bot#92]
A command which returns a random number between 1 and the given number. If no number is given, returns a random number between 1 and 10.

**Comment by langel** [comment]
it looks like your pull request contains your timezone work
i suggest copying your !roll code into a new branch from master and submitting that
i totally stalled the bot out with: `!roll 134029375209357d2309547203957209357`
the +/- modifier should probably always be available or never available; seems to only work with the `d` present

**Comment by langel** [comment]
i couldn't help myself and refactored your code quite a bit
https://github.com/langel/botb_irc_bot/commit/b87c95b21f160b538a63dff76319a8ea2ee0668d
